/** NFR-SEC-01: the complete permission catalogue. Seeded into the Permission table. */
export const PERMISSIONS = [
  // system / admin
  ['admin.users', '사용자 관리'],
  ['admin.roles', '역할·권한 관리'],
  ['admin.settings', '정책·시스템 설정'],
  ['admin.audit', '감사로그 조회'],
  ['admin.jobs', '실패작업 조회·재시도'],
  ['admin.migration', '데이터 이관 실행'],
  // master data (BAS)
  ['master.read', '기초정보 조회'],
  ['master.write', '기초정보 등록·수정'],
  ['master.export', '기초정보 내보내기'],
  // sales / purchase (SLS)
  ['sales.read', '매출·매입 조회'],
  ['sales.write', '매출·매입 등록·수정'],
  ['sales.confirm', '매출·매입 확정'],
  ['sales.cancel', '매출·매입 취소'],
  ['sales.export', '매출·매입 내보내기'],
  ['purchase.read', '구매요청·발주 조회'],
  ['purchase.write', '구매요청·발주 등록·수정'],
  ['purchase.confirm', '발주·매입 확정'],
  ['purchase.cancel', '발주·매입 취소'],
  ['settlement.read', '채권채무·수금지급 조회'],
  ['settlement.write', '수금·지급 등록'],
  ['settlement.confirm', '수금·지급 확정'],
  // inventory (INV)
  ['inventory.read', '재고 조회'],
  ['inventory.write', '입출고·이동 등록'],
  ['inventory.confirm', '입출고·이동 확정'],
  ['inventory.cancel', '입출고·이동 취소'],
  ['inventory.count', '재고 실사·조정'],
  ['inventory.valuation', '재고 평가·월마감'],
  ['inventory.export', '재고 내보내기'],
  // accounting (ACC)
  ['accounting.read', '회계 조회'],
  ['accounting.write', '회계전표 등록·수정'],
  ['accounting.confirm', '회계전표 확정'],
  ['accounting.cancel', '회계전표 취소·역분개'],
  ['accounting.rules', '분개규칙 관리'],
  ['accounting.close', '회계 마감'],
  ['period.reopen', '마감 해제'],
  ['accounting.export', '회계 내보내기'],
  // approval (APV)
  ['approval.use', '결재 기안·처리'],
  ['approval.admin', '결재 양식·결재선 관리'],
  // HR (HRM) — NFR-SEC-02 keeps these separate from business permissions
  ['hr.self', '본인 인사정보 조회'],
  ['hr.read', '전 직원 인사정보 조회'],
  ['hr.write', '인사정보 등록·수정·발령'],
  ['hr.sensitive.read', '주민번호·계좌번호 복호화 조회'],
  ['hr.attendance', '근태 관리'],
  ['hr.leave', '휴가·연차 관리'],
  ['hr.export', '인사정보 내보내기'],
  // reports (RPT)
  ['report.read', '보고서 조회'],
  ['report.export', '보고서 내보내기'],
] as const satisfies readonly (readonly [string, string])[];

export type PermissionCode = (typeof PERMISSIONS)[number][0];

export const moduleOf = (code: string): string => code.split('.')[0] ?? 'system';

/** Seeded roles (docs/security-model.md §3). */
export const ROLE_PRESETS: Record<string, { name: string; permissions: string[] | '*' }> = {
  admin: { name: '시스템 관리자', permissions: '*' },
  manager: {
    name: '경영진',
    permissions: [
      'master.read',
      'sales.read',
      'sales.export',
      'purchase.read',
      'settlement.read',
      'inventory.read',
      'inventory.export',
      'accounting.read',
      'accounting.export',
      'approval.use',
      'hr.self',
      'hr.read',
      'report.read',
      'report.export',
      'admin.audit',
    ],
  },
  sales: {
    name: '영업',
    permissions: [
      'master.read',
      'sales.read',
      'sales.write',
      'sales.confirm',
      'sales.cancel',
      'sales.export',
      'settlement.read',
      'settlement.write',
      'inventory.read',
      'approval.use',
      'hr.self',
      'report.read',
      'report.export',
    ],
  },
  purchasing: {
    name: '구매',
    permissions: [
      'master.read',
      'master.write',
      'purchase.read',
      'purchase.write',
      'purchase.confirm',
      'purchase.cancel',
      'sales.read',
      'inventory.read',
      'settlement.read',
      'approval.use',
      'hr.self',
      'report.read',
    ],
  },
  inventory: {
    name: '물류·재고',
    permissions: [
      'master.read',
      'inventory.read',
      'inventory.write',
      'inventory.confirm',
      'inventory.cancel',
      'inventory.count',
      'inventory.export',
      'sales.read',
      'approval.use',
      'hr.self',
      'report.read',
    ],
  },
  accounting: {
    name: '회계',
    permissions: [
      'master.read',
      'sales.read',
      'purchase.read',
      'settlement.read',
      'settlement.write',
      'settlement.confirm',
      'inventory.read',
      'inventory.valuation',
      'accounting.read',
      'accounting.write',
      'accounting.confirm',
      'accounting.cancel',
      'accounting.rules',
      'accounting.close',
      'accounting.export',
      'approval.use',
      'hr.self',
      'report.read',
      'report.export',
    ],
  },
  hr: {
    name: '인사',
    permissions: [
      'hr.self',
      'hr.read',
      'hr.write',
      'hr.sensitive.read',
      'hr.attendance',
      'hr.leave',
      'hr.export',
      'approval.use',
      'approval.admin',
      'report.read',
      'admin.users',
    ],
  },
  viewer: {
    name: '조회전용',
    permissions: [
      'master.read',
      'sales.read',
      'purchase.read',
      'settlement.read',
      'inventory.read',
      'accounting.read',
      'report.read',
      'hr.self',
      'approval.use',
    ],
  },
};
